### ISSUE TITLE
v1.3.0 Release TODO

### ISSUE THREAD

**Issue by tonini** [tonini/alchemist.el#139]
#### Checklist for v1.3.0 release

- [x] Refactoring / refining of `alchemist-server.el`
- [x] Refining of `alchemist-report.el` (add missing comments for functions and variables)
- [x] Refactor `alchemist-mix.el` (what's about interactive functions without key binding, since `alchemist-mix` speedup are they even useful?)
- [x] Use `declare-function` just with `eval-when-compile` (package wide)
- [x] Add send input functionality to `alchemist-mix`
- [ ] ~~`alchemist-goto--string-at-point-p` uses interactive `end-of-buffer` in context of `parse-partial-sexp`, otherwise `parse-partial-sexp` doesn't parse over the whole buffer.~~
