### ISSUE TITLE
v1.4.0 Release TODO

### ISSUE THREAD

**Issue by tonini** [tonini/alchemist.el#149]
## Checklist for v1.4.0 release

- [x]  Refactoring / refining of `alchemist-server.el`.
- [x] `alchemist-help` should handle context based search for help.
- [x] `alchemist-report` ability to run in background. (popup when failed)
- [x] Add missing documentation for `alchemist elixir server`.
- [x] Add render functions to `alchemist-execute`, which calls `alchemist-report-run`.
- [x] Handle exception when calling for documentation for attributes (example: `@behaviour`)
      `Code.eval_string` will fail
       `** (ArgumentError) could not call get_attribute on module Alchemist.Documentation because it was already compiled`
